#!/usr/bin/env bash

git pull

pull=$?

if [[ "$pull" -ne 0 ]]
then
        echo "Fix git pull error as seen in the following output, and run script again"
        echo "$pull"
        exit 1
fi

git add .

# Prompt for commit message
echo "Please enter your commit message: "
read -r message

git commit -m "$message"
git push origin HEAD

